paypal:
  client-id: AYTFSkJ2RCQPNgh4wfRO8csYOXQr3MefaV--epC-BHzvl722KmOMG3dNCrM44f5ITZM0KXqsLPW4lwZa
  client-secret: EPyMW_iSjtzrxQJOEySuGdG3BMWLR5529imZAfkI23EUzT87CcNp7ywgrqyQpHS0so79zke3EH9YcIJa
  mode: sandbox